groups:
  - name: fastapi_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"
  
  - name: ptiik_insight_ml_alerts
    rules:
      - alert: ModelAccuracyLow
        expr: model_accuracy < 0.7
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Model accuracy is below threshold"
          description: "Model accuracy has been below 0.7 for more than 5 minutes. Current value: {{ $value }}"
      
      - alert: HighPredictionErrors
        expr: rate(model_prediction_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High prediction error rate"
          description: "Prediction error rate is {{ $value }} errors/second over the last 5 minutes"
      
      - alert: APIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API latency is high"
          description: "95th percentile latency is {{ $value }} seconds"

      - alert: ModelPredictionFailure
        expr: increase(model_prediction_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Model prediction failures detected"
          description: "{{ $value }} model prediction failures in the last 5 minutes"

      - alert: LowModelAccuracy
        expr: model_accuracy < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Model accuracy is low"
          description: "Model accuracy is {{ $value }}, below threshold of 0.7"

      - alert: ScrapingFailure
        expr: increase(scraping_errors_total[10m]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Multiple scraping failures detected"
          description: "{{ $value }} scraping failures in the last 10 minutes"
