apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    jsonData:
      timeInterval: 5s
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}
    version: 1
    editable: false
